# Generated by Django 4.1.1 on 2022-10-02 18:27

import chronos.watches.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile', validators=[
                chronos.watches.validators.file_size]),
        ),
    ]
