# Generated by Django 4.1.1 on 2022-10-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_watch_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
