# Generated by Django 4.1.1 on 2022-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='condition',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watches',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
