# Generated by Django 4.1.1 on 2022-10-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_remove_postcomment_author_remove_postcomment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='watchcomment',
            name='watches',
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
        migrations.DeleteModel(
            name='WatchComment',
        ),
    ]
