# Generated by Django 4.1.1 on 2022-10-13 12:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={},
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=tinymce.models.HTMLField(max_length=300),
        ),
    ]
