# Generated by Django 4.1.1 on 2022-10-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postcomment_options_alter_postcomment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.TextField(max_length=300),
        ),
    ]
