# Generated by Django 4.1.1 on 2022-10-07 15:48

import chronos.watches.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('reference_number', models.CharField(max_length=30)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2022)])),
                ('style', models.CharField(choices=[('Pocket', 'Pocket'), ('Railroad', 'Railroad'), ('Dress', 'Dress'), ('Field', 'Field'), ('Aviator', 'Aviator'), ('Dive', 'Dive'), ('Racing', 'Racing'), ('Digital', 'Digital'), ('Smart ', 'Smart'), ('Fashion', 'Fashion')], max_length=8)),
                ('condition', models.TextField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='watches', validators=[chronos.watches.validators.file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='watch_likes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'watches',
            },
        ),
        migrations.CreateModel(
            name='WatchComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='watches.watches')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
