# Generated by Django 4.1.1 on 2022-10-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchcomment',
            options={},
        ),
    ]
