# Generated by Django 4.1.1 on 2022-10-21 14:18

import chronos.watches.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_watch_price_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watches', validators=[
                chronos.watches.validators.file_size]),
        ),
        migrations.AlterField(
            model_name='watches',
            name='price_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watches',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
